"""Demo catalog shared by mock providers and DB seed."""

from __future__ import annotations

from typing import Any

CatalogRow = dict[str, Any]

POSTER = "https://picsum.photos/seed/{slug}/300/450"
BACKDROP = "https://picsum.photos/seed/{slug}-bg/1280/720"

CATALOG: list[CatalogRow] = [
    dict(
        key="matrix",
        title="Матрица",
        original_title="The Matrix",
        year=1999,
        content_type="movie",
        description="Хакер Нео узнаёт, что его реальность — симуляция, и возглавляет борьбу за свободу человечества.",  # noqa: E501
        genres=["фантастика", "боевик"],
        rating_kinopoisk=8.5,
        rating_imdb=8.7,
        tmdb_id=603,
        runtime_minutes=136,
        popularity=98,
    ),
    dict(
        key="interstellar",
        title="Интерстеллар",
        original_title="Interstellar",
        year=2014,
        content_type="movie",
        description="Путешествие через червоточину в поисках нового дома для человечества.",
        genres=["фантастика", "драма"],
        rating_kinopoisk=8.7,
        rating_imdb=8.7,
        tmdb_id=157336,
        runtime_minutes=169,
        popularity=97,
    ),
    dict(
        key="dune",
        title="Дюна",
        original_title="Dune",
        year=2021,
        content_type="movie",
        description="Пол Атрейдес отправляется на Арракис, где решается судьба вселенной.",
        genres=["фантастика", "приключения"],
        rating_kinopoisk=7.8,
        rating_imdb=8.0,
        tmdb_id=438631,
        runtime_minutes=155,
        popularity=90,
    ),
    dict(
        key="oppenheimer",
        title="Оппенгеймер",
        original_title="Oppenheimer",
        year=2023,
        content_type="movie",
        description="История создателя атомной бомбы Роберта Оппенгеймера.",
        genres=["драма", "история"],
        rating_kinopoisk=8.1,
        rating_imdb=8.3,
        tmdb_id=872585,
        runtime_minutes=180,
        popularity=92,
    ),
    dict(
        key="brat2",
        title="Брат 2",
        original_title="Brother 2",
        year=2000,
        content_type="movie",
        description="Данила Багров отправляется в Чикаго выручать брата.",
        genres=["криминал", "драма"],
        rating_kinopoisk=8.1,
        rating_imdb=7.7,
        tmdb_id=86987,
        runtime_minutes=122,
        popularity=88,
    ),
    dict(
        key="gentlemen",
        title="Джентльмены",
        original_title="The Gentlemen",
        year=2019,
        content_type="movie",
        description="Наркобарон пытается продать империю и выйти из игры.",
        genres=["криминал", "комедия"],
        rating_kinopoisk=8.5,
        rating_imdb=7.8,
        tmdb_id=522938,
        runtime_minutes=113,
        popularity=89,
    ),
    dict(
        key="slovo",
        title="Слово пацана. Кровь на асфальте",
        original_title="",
        year=2023,
        content_type="series",
        description="Казань конца 80-х: подростковые группировки делят улицы.",
        genres=["криминал", "драма"],
        rating_kinopoisk=8.4,
        rating_imdb=7.9,
        tmdb_id=242789,
        runtime_minutes=50,
        popularity=95,
    ),
    dict(
        key="squid",
        title="Игра в кальмара",
        original_title="Squid Game",
        year=2021,
        content_type="series",
        description="456 должников играют в детские игры на выживание ради приза.",
        genres=["триллер", "драма"],
        rating_kinopoisk=7.5,
        rating_imdb=8.0,
        tmdb_id=93405,
        runtime_minutes=55,
        popularity=91,
    ),
    dict(
        key="wednesday",
        title="Уэнсдэй",
        original_title="Wednesday",
        year=2022,
        content_type="series",
        description="Уэнсдэй Аддамс расследует тайны академии Невермор.",
        genres=["фэнтези", "комедия"],
        rating_kinopoisk=7.6,
        rating_imdb=8.5,
        tmdb_id=119051,
        runtime_minutes=45,
        popularity=93,
    ),
    dict(
        key="avatar2",
        title="Аватар: Путь воды",
        original_title="Avatar: The Way of Water",
        year=2022,
        content_type="movie",
        description="Джейк Салли и Нейтири защищают Пандору от новой угрозы.",
        genres=["фантастика", "приключения"],
        rating_kinopoisk=7.4,
        rating_imdb=7.6,
        tmdb_id=76600,
        runtime_minutes=192,
        popularity=87,
    ),
    dict(
        key="barbie",
        title="Барби",
        original_title="Barbie",
        year=2023,
        content_type="movie",
        description="Барби покидает Барбиленд и открывает реальный мир.",
        genres=["комедия", "фэнтези"],
        rating_kinopoisk=6.9,
        rating_imdb=6.9,
        tmdb_id=346698,
        runtime_minutes=114,
        popularity=85,
    ),
    dict(
        key="wick4",
        title="Джон Уик 4",
        original_title="John Wick: Chapter 4",
        year=2023,
        content_type="movie",
        description="Джон Уик бросает вызов Правлению, чтобы обрести свободу.",
        genres=["боевик", "триллер"],
        rating_kinopoisk=7.4,
        rating_imdb=7.7,
        tmdb_id=603692,
        runtime_minutes=169,
        popularity=86,
    ),
    dict(
        key="cheburashka",
        title="Чебурашка",
        original_title="",
        year=2023,
        content_type="movie",
        description="Мохнатый зверёк из апельсиновой рощи находит дом и друзей.",
        genres=["комедия", "семейный"],
        rating_kinopoisk=7.3,
        rating_imdb=6.8,
        tmdb_id=1045944,
        runtime_minutes=113,
        popularity=84,
    ),
    dict(
        key="vyzov",
        title="Вызов",
        original_title="The Challenge",
        year=2023,
        content_type="movie",
        description="Первый фильм, снятый в космосе: хирург летит спасать космонавта.",
        genres=["драма"],
        rating_kinopoisk=7.0,
        rating_imdb=6.5,
        tmdb_id=962946,
        runtime_minutes=164,
        popularity=78,
    ),
    dict(
        key="cyberderevnya",
        title="Кибердеревня",
        original_title="",
        year=2023,
        content_type="series",
        description="Фермер Николай с роботами пытается спасти хозяйство в 2100 году.",
        genres=["фантастика", "комедия"],
        rating_kinopoisk=7.9,
        rating_imdb=7.4,
        tmdb_id=241660,
        runtime_minutes=30,
        popularity=88,
    ),
    dict(
        key="trigger",
        title="Триггер",
        original_title="",
        year=2018,
        content_type="series",
        description="Психолог Артём Стрелецкий лечит пациентов шоковой терапией.",
        genres=["драма"],
        rating_kinopoisk=8.0,
        rating_imdb=7.6,
        tmdb_id=98701,
        runtime_minutes=50,
        popularity=82,
    ),
    dict(
        key="kuhnya",
        title="Кухня",
        original_title="",
        year=2012,
        content_type="series",
        description="Комедия о жизни элитного ресторана и его шефа.",
        genres=["комедия"],
        rating_kinopoisk=8.2,
        rating_imdb=7.8,
        tmdb_id=65515,
        runtime_minutes=25,
        popularity=86,
    ),
    dict(
        key="smeshariki",
        title="Смешарики",
        original_title="",
        year=2004,
        content_type="series",
        description="Круглые друзья попадают в добрые и поучительные истории.",
        genres=["мультфильм", "семейный"],
        rating_kinopoisk=8.3,
        rating_imdb=7.9,
        tmdb_id=15154,
        runtime_minutes=11,
        popularity=83,
    ),
    dict(
        key="friends",
        title="Друзья",
        original_title="Friends",
        year=1994,
        content_type="series",
        description="Шестеро друзей, кофейня и десять сезонов легенды.",
        genres=["комедия"],
        rating_kinopoisk=8.9,
        rating_imdb=8.9,
        tmdb_id=1668,
        runtime_minutes=22,
        popularity=94,
    ),
    dict(
        key="breaking",
        title="Во все тяжкие",
        original_title="Breaking Bad",
        year=2008,
        content_type="series",
        description="Учитель химии становится наркобароном Альбукерке.",
        genres=["криминал", "драма"],
        rating_kinopoisk=8.9,
        rating_imdb=9.5,
        tmdb_id=1396,
        runtime_minutes=49,
        popularity=96,
    ),
    dict(
        key="office",
        title="Офис",
        original_title="The Office",
        year=2005,
        content_type="series",
        description="Мокьюментари о самом странном офисе Скрентона.",
        genres=["комедия"],
        rating_kinopoisk=8.4,
        rating_imdb=9.0,
        tmdb_id=2316,
        runtime_minutes=22,
        popularity=90,
    ),
    dict(
        key="aot",
        title="Атака титанов",
        original_title="Attack on Titan",
        year=2013,
        content_type="series",
        description="Человечество прячется за стенами от гигантских титанов.",
        genres=["аниме", "фэнтези"],
        rating_kinopoisk=8.6,
        rating_imdb=9.1,
        tmdb_id=1429,
        runtime_minutes=24,
        popularity=92,
    ),
    dict(
        key="potter",
        title="Гарри Поттер и философский камень",
        original_title="Harry Potter",
        year=2001,
        content_type="movie",
        description="Мальчик узнаёт, что он волшебник, и едет в Хогвартс.",
        genres=["фэнтези", "приключения"],
        rating_kinopoisk=8.2,
        rating_imdb=7.6,
        tmdb_id=671,
        runtime_minutes=152,
        popularity=91,
    ),
    dict(
        key="cosmos",
        title="Космос за 15 минут: чёрные дыры",
        original_title="",
        year=2024,
        content_type="video",
        description="Короткое и понятное видео о чёрных дырах и горизонте событий.",
        genres=["документалки"],
        rating_kinopoisk=None,
        rating_imdb=None,
        tmdb_id=None,
        runtime_minutes=15,
        popularity=72,
    ),
    dict(
        key="standup",
        title="Открытый микрофон: лучший стендап месяца",
        original_title="",
        year=2024,
        content_type="video",
        description="Подборка лучших выступлений месяца с открытого микрофона.",
        genres=["стендап", "комедия"],
        rating_kinopoisk=None,
        rating_imdb=None,
        tmdb_id=None,
        runtime_minutes=45,
        popularity=70,
    ),
    dict(
        key="prostokvashino",
        title="Простоквашино",
        original_title="",
        year=2018,
        content_type="series",
        description="Новые приключения в любимой деревне.",
        genres=["мультфильм", "семейный"],
        rating_kinopoisk=7.1,
        rating_imdb=6.9,
        tmdb_id=79801,
        runtime_minutes=11,
        popularity=76,
    ),
]


def with_images(row: CatalogRow) -> CatalogRow:
    slug = row["key"]
    return {
        **row,
        "poster_url": POSTER.format(slug=slug),
        "backdrop_url": BACKDROP.format(slug=slug),
    }


FULL_CATALOG: list[CatalogRow] = [with_images(r) for r in CATALOG]
BY_KEY: dict[str, CatalogRow] = {str(r["key"]): r for r in FULL_CATALOG}
